export const REDUCER_ACTION_TYPE = {
  SELL_AMOUNT: "SELL_AMOUNT",
  BUY_AMOUNT: "BUY_AMOUNT",
  SELL_TOKEN: "SELL_TOKEN",
  BUY_TOKEN: "BUY_TOKEN",
  LIMIT_PRICE: "LIMIT_PRICE",
  MARKUP: "MARKUP",
  EXPIRY: "EXPIRY",
  SWAP: "SWAP",
  UPDATE_BUY_BALANCE: "UPDATE_BUY_BALANCE",
  UPDATE_SELL_BALANCE: "UPDATE_SELL_BALANCE",
} as const;
